import {
    SmdAvatar,
    SmdAvatarPair,
    SmdBlockingLoader,
    SmdBottomBanner,
    SmdButton,
    SmdCalendar,
    SmdCard,
    SmdCheckbox,
    SmdDateInput,
    SmdDatePicker,
    SmdDateTextInput,
    SmdDivider,
    SmdDropdownList,
    SmdDropdownListItem,
    SmdHeader,
    SmdImageWithOverlay,
    SmdInput,
    SmdListItem,
    SmdLoading,
    SmdLoadingSpinner,
    SmdLogo,
    SmdMoreOptions,
    SmdNavigation,
    SmdNavigationItem,
    SmdNavigationSubmenu,
    SmdNote,
    SmdNotification,
    SmdOneColumnLayout,
    SmdOtpInputText,
    SmdPhoneInput,
    SmdPopper,
    SmdRadio,
    SmdRibbon,
    SmdSearch,
    SmdSelect,
    SmdSpacer,
    SmdStatusBar,
    SmdStepper,
    SmdSwitch,
    SmdTabLink,
    SmdTabs,
    SmdTag,
    SmdTextarea,
    SmdThumbnail,
    SmdThumbnailMS,
    SmdThumbnailNav,
    SmdThumbnailNavItem,
    SmdTimePicker,
    SmdTopBanner,
    SmdTwoColumnLayout,
} from 'smd-scaffold';

// https://stackoverflow.com/questions/69010567/how-to-make-vscode-recognize-global-component-in-vue
// https://stackoverflow.com/questions/70980658/how-can-i-make-volar-aware-of-globally-available-components-in-vue-3

declare module 'vue' {
    export interface GlobalComponents {
        SmdAvatar: typeof SmdAvatar,
        SmdAvatarPair: typeof SmdAvatarPair,
        SmdBlockingLoader: typeof SmdBlockingLoader,
        SmdBottomBanner: typeof SmdBottomBanner,
        SmdButton: typeof SmdButton,
        SmdCalendar: typeof SmdCalendar,
        SmdCard: typeof SmdCard,
        SmdCheckbox: typeof SmdCheckbox,
        SmdDateInput: typeof SmdDateInput,
        SmdDatePicker: typeof SmdDatePicker,
        SmdDateTextInput: typeof SmdDateTextInput,
        SmdDivider: typeof SmdDivider,
        SmdDropdownList: typeof SmdDropdownList,
        SmdDropdownListItem: typeof SmdDropdownListItem,
        SmdHeader: typeof SmdHeader,
        SmdImageWithOverlay: typeof SmdImageWithOverlay,
        SmdInput: typeof SmdInput,
        SmdListItem: typeof SmdListItem,
        SmdLoading: typeof SmdLoading,
        SmdLoadingSpinner: typeof SmdLoadingSpinner,
        SmdLogo: typeof SmdLogo,
        SmdMoreOptions: typeof SmdMoreOptions,
        SmdNavigation: typeof SmdNavigation,
        SmdNavigationItem: typeof SmdNavigationItem,
        SmdNavigationSubmenu: typeof SmdNavigationSubmenu,
        SmdNote: typeof SmdNote,
        SmdNotification: typeof SmdNotification,
        SmdOneColumnLayout: typeof SmdOneColumnLayout,
        SmdOtpInputText: typeof SmdOtpInputText,
        SmdPhoneInput: typeof SmdPhoneInput,
        SmdPopper: typeof SmdPopper,
        SmdRadio: typeof SmdRadio,
        SmdRibbon: typeof SmdRibbon,
        SmdSearch: typeof SmdSearch,
        SmdSelect: typeof SmdSelect,
        SmdSpacer: typeof SmdSpacer,
        SmdStatusBar: typeof SmdStatusBar,
        SmdStepper: typeof SmdStepper,
        SmdSwitch: typeof SmdSwitch,
        SmdTabLink: typeof SmdTabLink,
        SmdTabs: typeof SmdTabs,
        SmdTag: typeof SmdTag,
        SmdTextarea: typeof SmdTextarea,
        SmdThumbnail: typeof SmdThumbnail,
        SmdThumbnailMS: typeof SmdThumbnailMS,
        SmdThumbnailNav: typeof SmdThumbnailNav,
        SmdThumbnailNavItem: typeof SmdThumbnailNavItem,
        SmdTimePicker: typeof SmdTimePicker,
        SmdTopBanner: typeof SmdTopBanner,
        SmdTwoColumnLayout: typeof SmdTwoColumnLayout,
    }
}
